openapi: 3.0.3
info:
  title: Employee API Specification
  description: A simple Employee API
  version: 1.0-SNAPSHOT
servers:
  - url: 'http://localhost:8080'
paths:
  /employee:
    get:
      tags:
        - employee-controller
      summary: Get employee information
      operationId: read
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Empolyee not found
          content:
            application/*/*:
              schema:
                type: string
    post:
      tags:
        - employee-controller
      summary: create new employee
      operationId: create
      requestBody:
        description: Account number and desired amount to deposit
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '404':
          description: Employee not found
          content:
            application/*/*:
              schema:
                type: string
    put:
      tags:
        - employee-controller
      summary: update an employee
      operationId: update
      requestBody:
        description: Account number and desired amount to deposit
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '404':
          description: Employee not found
          content:
            application/*/*:
              schema:
                type: string
  '/employee/{employeeId}':
    get:
      tags:
        - employee-controller
      summary: get an employee
      operationId: get an employee by id
      parameters:
        - name: employeeId
          in: path
          description: ID of employee to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '404':
          description: Employee not found
          content:
            application/*/*:
              schema:
                type: string
components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
        lastName:
          type: string
        firstName:
          type: string
